name: Pandoc

on: [push]

jobs:
    convert_via_pandoc:
      name: Convert via Pandoc
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - uses: maxheld83/pandoc@v2
          with:
            args: "-f markdown -t pdf -o README.pdf README.md"
