name: Pandoc

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: maxheld83/pandoc
    - name: Pandoc
      run: pandoc -f markdown -t pdf -o README.pdf README.md
